apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-app-service
spec:
  # Exposes the service on a static port on each node
  type: NodePort 
  selector:
    app: my-nextjs-app # Must match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80 # Port on the service
      targetPort: 3000 # Port on the pods
